### ISSUE TITLE
Conflict with Ruby Extension in html.erb files

### ISSUE THREAD

**Issue by julihermes** [bung87/vscode-rails#1]
Installing this extension makes the Ruby Extension not work anymore in html.erb files. Snippets like "if", "for", "unless" and etc not work, only the snippets from your extension works.

_**[update]**_
loses Syntax Highlighting too.

**Comment by bung87** [comment]
I'v taken grammers from https://github.com/vortizhe/vscode-ruby-erb,  you can uninstall it or https://github.com/craigmaslowski/vscode-erb.
