### ISSUE TITLE
Comment commands don't work in erb files

### ISSUE THREAD

**Issue by bbugh** [bung87/vscode-rails#16]
I hadn't realized how many times a day I type `Cmd+/` until it doesn't work!

**Describe the bug**

The comment commands work in erb files - Block Comment, Line Comment, etc. The commands do not do anything when activated via shortcut keys or the Command Palette.

**To Reproduce**
1. Open a Rails view `.erb.html`
2. Select some lines of code
3. Try to comment out a block or line (Command Palette => Toggle Line Comment, or Toggle Block Comment)

**Expected behavior**

The line or block should toggle the comments, preferably with HTML comments `<!-- ... -->` rather than ERB `<%# ... %>` comments.

**Comment by bung87** [comment]
Hi ,thanks ,I checked this problem, it does exist ,it is complicated ,I'll check somewhere see if I can find a solution.the best results I can imaging is the comment behavior depends the mouse cursor position.supporting all html ,js ruby comments.

**Comment by bung87** [comment]
I release a patch version ,using `begin` `end` for bock comment ,feel free reopen this issue if you have better solution.
