### ISSUE TITLE
Navigation not working when the parent folder is open

### ISSUE THREAD

**Issue by sanjibukai** [bung87/vscode-rails#18]
Hello,
The navigation between files is not working when I open code with a parent folder.

For example I have a folder `my_project` and inside that folder I did the `rails new my_rails_app`.
Something like that:
```
my_project/
 + my_rails_app/
   + app/
   + config/
   + db/
   ...
```
Do you know how it could be possible to navigate between the rails files?
Thank you.

**Comment by bung87** [comment]
you should open my_rails_app

**Comment by sanjibukai** [comment]
Thanks, but this doesn't suit my need at all..
If I've opened a parent folder, this is maybe because I'm working with other files..
Thank you for your plugin, but in the meantime for navigating files the following plugin https://marketplace.visualstudio.com/items?itemName=jemmyw.rails-fast-nav works like a charm..

**Comment by bung87** [comment]
Thank you,I checked the plugin source ,it needs multi times IO operation for detecting rails root. this is not my way currently.
