### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by szhu** [bung87/vscode-rails#21]
- Issue Type: `Performance`
- Extension Name: `rails`
- Extension Version: `0.8.5`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.30.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/Sean/bung87.rails-unresponsive.cpuprofile.txt` :warning:
[bung87.rails-unresponsive.cpuprofile.txt](https://github.com/bung87/vscode-rails/files/2729015/bung87.rails-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by szhu** [comment]
Why was this closed?

**Comment by bung87** [comment]
it duplicated with https://github.com/bung87/vscode-rails/issues/19
and provided similar profile log file,  I can not get enough information to make sure where the problem is.

**Comment by szhu** [comment]
Got it, thanks for the update!
