### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by lujanfernaud** [bung87/vscode-rails#29]
- Issue Type: `Performance`
- Extension Name: `rails`
- Extension Version: `0.8.7`
- OS Version: `Linux x64 4.15.0-45-generic`
- VSCode version: `1.31.1`

[bung87.rails-unresponsive.cpuprofile.txt](https://github.com/bung87/vscode-rails/files/2909207/bung87.rails-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by bung87** [comment]
thanks for reporting , it's been a while, I have no idea about this problem, could you provide more information help me out? like when this issue occurs?

**Comment by lujanfernaud** [comment]
Hey @bung87, thanks for working on this. I'm sorry for the delay.

I think it happened when switching from a Markdown file to a Ruby file (inside a Rails project).

It also happened a few times before, but I don't remember the conditions.
