### ISSUE TITLE
There are extra ending erb tags in the form_for and form_for snippets

### ISSUE THREAD

**Issue by yehudamakarov** [bung87/vscode-rails#3]
```
<%= form_for( variable , remote: true) do |f| %> %>
    true
<% end %>
```

Whats with that duplicate tag? I can't edit my own copy of the extension on my own. Please fix it? Same for the form_tag snippet

**Comment by bung87** [comment]
the **true**  inside block ?
I dont see extra ending tag there

**Comment by yehudamakarov** [comment]
I’m not sure what you mean. Look at the form_for and form_tag snippets. The era tags to start the iteration have extra closing tags on both. Try to use one of the snippets in a file.

**Comment by bung87** [comment]
http://api.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html
I checked both `form_for ` and `form_tag `
`form_for ` then tab results
```
<%= form_for( variable , remote: true) do |f| %> %>
true
<% end %>
```
what's wrong there?

**Comment by yehudamakarov** [comment]
`<%= form_for @person do |f| %>` = good
`<%= form_for @person do |f| %> %>` = bad.
The extra ending tag is not supposed to be there.

**Comment by bung87** [comment]
ah I see `%>` , thank you ! I just treat **ending tag** as `<% end %>` sorry for mine poor english.

**Comment by yehudamakarov** [comment]
OHHH :) <3. 
It's okay man. I love your package so I want you to fix it. 

If your extension is on, none of my personal snippets will work for html.erb (Someone else opened that issue.)

So when you fix it, I can update it, and then use the extension. :)

**Comment by bung87** [comment]
glad to hear you love this project! :)
