### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by GreeKatrina** [bung87/vscode-rails#40]
- Issue Type: `Performance`
- Extension Name: `rails` [link](https://marketplace.visualstudio.com/items?itemName=rebornix.Ruby)
- Extension Version: `0.13.0`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.33.1`

This issue keeps happening while editing ruby code.

[bung87.rails-unresponsive.cpuprofile.txt](https://github.com/bung87/vscode-rails/files/3086752/bung87.rails-unresponsive.cpuprofile.txt)

![Screen Shot 2019-04-16 at 4 31 29 PM](https://user-images.githubusercontent.com/6021090/56242142-950aff00-6065-11e9-98dc-c344c9d747df.png)

**Comment by GreeKatrina** [comment]
The code I was editing looked similar to this:

```ruby
module Parent
  module Child
    ATTRIBUTES = %w(
      attr_a
      # ...
    ).freeze

    CustomErrorA = Class.new(StandardError)

    def self.foo!(a:, b:, c: Time.zone.now)
      raise CustomErrorA unless b.in?(Bar::Baz::ALL)

      new_foo = a.with_lock do
        raise CustomErrorA if a.date < c
            
        a.create!(
          # ...
        )
      end
    end      
  end
end
```

It seemed to be tripping up when I was messing with raising the errors. Hope that helps.

**Comment by bung87** [comment]
thanks for your reporting and details, will check it later.

**Comment by bung87** [comment]
see discuss here https://github.com/bung87/vscode-rails/issues/19#issuecomment-489278939
