### ISSUE TITLE
Running the contributed command: 'Rails:Document' failed.

### ISSUE THREAD

**Issue by EthanZeigler** [bung87/vscode-rails#44]
**Describe the bug**
Side view documentation fails on macOS
**please use simple vocabulary words as I'm not a native english speaker**

**To Reproduce**
1. Press option+FN+F1
2. Title error appears
`Running the contributed command: 'Rails:Document' failed.`
**Expected behavior**
Documentation window opens

**Additional context**
VSCode about:
- Version: 1.37.0
- Commit: 036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8
- Date: 2019-08-08T01:22:37.660Z
- Electron: 4.2.7
- Chrome: 69.0.3497.128
- Node.js: 10.11.0
- V8: 6.9.427.31-electron.0
- OS: Darwin x64 18.7.0

**Comment by bung87** [comment]
fixed version 0.16.1
