### ISSUE TITLE
FileTypeHandlers.get(...) is not a function

### ISSUE THREAD

**Issue by seanders** [bung87/vscode-rails#45]
**Describe the bug**
Every so often, my extension host terminates unexpectedly. Seems to be failing because of this:

```
VS Code Extension host terminated unexpectedly

[Extension Host] TypeError: FileTypeHandlers.get(...) is not a function	at Object.definitionLocation (/Users/sean.miller/.vscode/extensions/bung87.rails-0.13.0/out/src/rails_definition.js:345:42)	at RailsCompletionItemProvider.
```

**To Reproduce**
I don't know what the specific steps are to reproduce the problem.

**Expected behavior**
It does not throw an error.

**Screenshots**
Don't have any yet.

**Additional context**

**Comment by lgarron** [comment]
I see the same error every single time I try to go to a definition in a moderately large repo (going to the definition is never successful).
