### ISSUE TITLE
Cannot prevent auto-formatting

### ISSUE THREAD

**Issue by johnpash** [bung87/vscode-rails#50]
**Describe the bug**
A recent update to this extension is now automatically formatting `.html.erb` files.

I've added the following to `settings.json`, but it's not working.
```json
"[html.erb]": {
  "editor.formatOnSave": false
},
```

I've had to disable this extension because one line changes are now causing entire files to be reformatted, making the git history very difficult to parse.

Is there a different setting that I've missed to turn off this feature?

**Comment by bung87** [comment]
it's under .vscode/formatter.json 
```
{
    "onSave":false
}
```
I will consider merge `editor.formatOnSave` , thank your for reporting this problem.

**Comment by alagos** [comment]
Having the same issue and `"onSave":false` fixed it.
Just commenting to be notified when this be merged into `editor.formatOnSave`, so I could remove `.vscode/formatter.json` file from my project.

**Comment by alagos** [comment]
Oh, it's formatting also on paste. 
Isn't like I can't adapt to it (nothing that a `cmd+z` after paste can't solve it), but I wonder why isn't using default spacing (I have 2, but is formatting with 4 spaces).

**Comment by bung87** [comment]
I just using a nodejs module that for formatting html, as so far I have not seen a extension without install extro gem for formatting.  I may also considering merge space option , will investing the node module api.

**Comment by nick-skriabin** [comment]
same here. and it also breaks the erb syntax preventing ruby code from execution

<img width="661" alt="image" src="https://user-images.githubusercontent.com/767890/76840102-afd28e80-6847-11ea-87b5-20ededdb304d.png">

**Comment by thisismydesign** [comment]
This caused me some headaches today. Auto formatting is not even mentioned in the readme. It would be great to mention it or make it disabled by default. Also, the editor settings should be surely respected.

Edit: well this doesn't solve it for me actually. Had to disable
`.vscode/settings.json`
```json
{
  "onSave": false,
}
```

Edit: yep, my bad wrong file

**Comment by bung87** [comment]
feel free reporting issue, I may consider publish new version more carefully. I remenber it can formating html.erb as it identified as html, but now it doest take affect, so I just found a js module fix the problem.
next version will fix these problem.

**Comment by alagos** [comment]
@thisismydesign wrong file, isn't `.vscode/settings.json` but `.vscode/formatter.json`.
FWIW, in the meantime a fix is done, I installed a previous version. Just go to your extensions tab and click the gear icon of the Rails extension:
<img width="550" alt="Screen Shot 2020-03-18 at 9 12 24 AM" src="https://user-images.githubusercontent.com/475834/76897483-b1a85a80-68f8-11ea-95ee-dfec18ba6632.png">
Then choose `0.13.2`

**Comment by scott** [comment]
Hello @bung87, I am still experiencing this problem when pasting or entering certain shortcuts (maybe other ways too), such as using the `<%` pry shortcut. As soon as I either cmd-paste or use a shortcut, boom my formatting is destroyed, same was would happen with saving.

**Comment by bung87** [comment]
have you try
```
{
    "editor.formatOnSave": false
}
```
maybe you have a global settings formatOnSave set as `true`
