### ISSUE TITLE
Running the contributed command: 'Rails:Document' failed

### ISSUE THREAD

**Issue by creativetags** [bung87/vscode-rails#51]
I'm seeing this in version 0.16.2

Press option+FN+F1
Title error appears
Running the contributed command: 'Rails:Document' failed.
Expected behaviour
Documentation window opens

**Comment by bung87** [comment]
this cause by it can't find a valid word range , your active editor selection may not contains any symbol, it fixed in 0.16.9 , it will open right panel give you similar message in this comment
