### ISSUE TITLE
ERB tags <% %>  are misplaced

### ISSUE THREAD

**Issue by hackhowtofaq** [bung87/vscode-rails#53]
**Describe the bug**

ERB tags <% %>  are misplaced breaking the page

**To Reproduce**
**Expected behavior**

**Screenshots**

**Comment by bung87** [comment]
the previous version intruduce this issue, I forgot whether or not published fixed version to vs market, I just published a new version now, check whether this problem still has ,thanks.

**Comment by hackhowtofaq** [comment]
So it was introduced in 0.16.2 and fixed in 0.16.3?

**Comment by bung87** [comment]
I assuming it fixed in 0.16.2 or 0.16.3, I cant recall, the version I described here is specific to source code ,git commits, I might manually change the version that does not publish to vscode market?, I cant sure.
