### ISSUE TITLE
[Suggestion] Keeping an up to date changelog

### ISSUE THREAD

**Issue by zarembas** [bung87/vscode-rails#54]
I'm really not trying to be rude and I know this is an open-source project and a one-man contribution, but considering it's fairly popular at 120k downloads, I find it a bit strange that it doesn't have a changelog. [CHANGELOG.md](https://github.com/bung87/vscode-rails/blob/dev/CHANGELOG.md) hasn't been updated in two years and the repo doesn't publish its releases. Every time VS Code shows an update I have to go through the codebase and check to see what every commit has changed. It also might look unprofessional to people starting out with Rails who might be put off by this. Weirdly enough the [Django extension](https://github.com/vscode-django/vscode-django) does the same thing.

@bung87 please take this as a suggestion, I really appreciate all the hard work you've been putting into this project ❤️

**Comment by bung87** [comment]
yeah, 120k that's also unexpected for me, as the number grow  it should consider more carefully to release a new version, including codes and docs, I'll keep that in mind, thanks for this nice suggesion. I'll keep this open for reminding me.
