### ISSUE TITLE
Why are EOF newlines being removed in HTML files?

### ISSUE THREAD

**Issue by weavermedia** [bung87/vscode-rails#55]
I want my files to be formatted on save and to keep newlines at EOF but when I save an HTML file the EOF newline is being removed. Doesn't happen for CSS, JS or Ruby files, just HTML. My settings:

```
{
  "files.insertFinalNewline": true,
  "html.format.endWithNewline": true,
  "editor.formatOnSave": true,
}
```

How can I track down the cause?

Extensions installed and enabled:
Rails 0.16.7
Ruby Solargraph 0.21.1
Slim 0.1.2
vscode-gemfile 0.4.0

**Comment by bung87** [comment]
first of all, this extension has no processing with pure html, the `html.erb` identified as language `html.erb` , so settings as "html.format.endWithNewline" will not work, second check https://github.com/bung87/vscode-rails/blob/dev/src/formatter.ts , the formatting processing will replace content, not sure `insertFinalNewline` will do after that or not.

**Comment by weavermedia** [comment]
From the linked file it looks like `js-beautify` was introduced on March 13, which makes sense.

I wasn't aware that this extension did any formatting. It's not mentioned in the docs. I would rather use my own choice of formatter that I install and control.

Checking the NPM docs for this module the defaults contain these options:
```
{
    ...
    "end_with_newline": false,
    "preserve_newlines": true,
    ...
}
```
Not sure whether newlines at the end of file should be preserved with these default settings or not. Seems like they should but the `end_with_newline` setting makes me think this is the issue.

Questions:
1. Can I disable `js-beautify` in this extension?
2. If not, would you consider making automatic formatting optional?
3. To get back to previous behavior, how do I pass custom options to `js-beautify`?
4. Or would you cosider making `js-beautify` obey the editor's `insertFinalNewLine` setting?

**Comment by weavermedia** [comment]
Testing `js-beautify` at https://beautifier.io I see that final newlines are indeed removed by default.

The `preserve_newlines` setting only applies to newlines within the body of the file. For newline(s) at the end of the file `end_with_newline` takes over and removes it/them.

**Comment by bung87** [comment]
Thinks for your Investigation! I'll consider let extension respect editor's configuration .

**Comment by bung87** [comment]
hi , I checked the behaviour , it will insert final line break when you setting `"files.insertFinalNewline": true,`, the insertion is called after formatting.

`"html.format.endWithNewline": true,` will not take effect as I said, the `html.erb` files identified as `html.erb` language. 

`"files.insertFinalNewline": true,` will affect every file extension, that make sense.

**Comment by bung87** [comment]
if you still have problem feel free to reopen.
