### ISSUE TITLE
Add option to opt-out of format-on-save

### ISSUE THREAD

**Issue by alphaone** [bung87/vscode-rails#62]
**Describe the bug**
I have _prettier_ configured to format all my files (including `html.erb` files). When installing the vscode-rails extension, prettier is not able to format my files anymore, because vscode-rails does the formatting on save.

It would be very helpful, if there would be an option to disable the format-on-save in vscode-rails.

**To Reproduce**
1. Setup VS code to use prettier (with extension for ruby and erb)
2. Open an already formatted `html.erb` file
3. Save
4. vscode-rails formats the file

**Expected behavior**
vscode-rails should not format the file.

**Comment by bung87** [comment]
I've add these configuration on version 0.17.1 . 
* `rails.editor.formatOnSave` and `rails.editor.[html.erb].formatOnSave` ,`rails.editor.[css.erb].formatOnSave`, `rails.editor.[scss.erb].formatOnSave`

**Comment by bung87** [comment]
please re-open if problem exists, close for now.

**Comment by alphaone** [comment]
Thanks, that seems to work. Thank you 🙏 

A short paragraph on the project's readme about the possible configuration options of the extension would maybe help others if they stumble over the similar problems.
