### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by CanosaLeandro** [bung87/vscode-rails#64]
- Issue Type: `Bug`
- Extension Name: `rails`
- Extension Version: `0.17.7`
- OS Version: `Linux x64 5.4.0-77-generic`
- VS Code version: `1.58.1`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 138,
		"activateCallTime": 1,
		"activateResolvedTime": 5,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "bung87.rails",
				"_lower": "bung87.rails"
			},
			"activationEvent": "onLanguage:ruby"
		}
	},
	"runtimeErrors": []
}
```

**Comment by bung87** [comment]
do you have other information ? screenshot or error message, I dont know the problem from this kind of info.

**Comment by bung87** [comment]
if you still have this problem in v0.17.8 pls reopen.
